language: python

python:
  - 3.5
  - 3.6

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  - poetry develop

# command to run tests
script:
  - poetry run pytest

# create coverage badge
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
